{% set name = "tsflex" %}
{% set version = "0.2.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsflex-{{ version }}.tar.gz
  sha256: d304aad69ac0be732af351904a96cd0fcc433561bed42f6d95a2ab5ed497487e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.10
  run:
    - dill >=0.3.3,<0.4.0
    - fastparquet >=0.6.3,<0.7.0
    - numpy >=1.19.0,<2.0.0
    - pandas >=1.2.3,<2.0.0
    - pathos >=0.2.7,<0.3.0
    - python >=3.6,<3.10
    - tqdm >=4.60.0,<5.0.0

test:
  imports:
    - tsflex
    - tsflex.chunking
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/predict-idlab/tsflex
  summary: Toolkit for flexible processing & feature extraction on time-series data
  license: MIT
  license_file: LICENSE
  doc_url: https://predict-idlab.github.io/tsflex/
  dev_url: https://github.com/predict-idlab/tsflex

extra:
  recipe-maintainers:
    - jvdd
    - jonasvdd
